[package]
name = "factorization"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "The open-source automation game, factorization"
keywords = ["game-engine", "rendering", "factorization"]
readme = "README.md"
repository = "https://github.com/MuffinGroup/factorization-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"
glium = "*"
image = "*"
maplit = "*"
