name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: executable-linux
          path: target/debug/factorization

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: executable-windows
          path: target/debug/factorization.exe
